"use client"
import { ChakraProvider, background, Box } from "@chakra-ui/react"
import Navbar from "@/components/Navbar"
import { Children } from "react"



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          <Navbar />
          <Box backgroundColor={'gray.800'}>
          {children}
          </Box>
        </ChakraProvider>

      </body>
    </html>
  )
}
